name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Set timezone
      run: echo "TZ='Europe/Berlin'" >> $GITHUB_ENV

    - name: Log Local Time
      run: node -e "console.log('本地时区时间:', new Date().toLocaleString())"
